### PR TITLE
Update gradle version to match react native v56

### PR DESCRIPTION
**Pull request by skb1129**
Tasks:
- Upgrade gradle to version 2.3.3.
- Set default `compileSdkVersion` to **25**, `buildToolsVersion` **25.0.3** and `targetSdkVersion` **25**.

These changes are respective to react native version 56+
I have also updated the Example to use react native version `0.56.1`

### CODE REVIEW

**Comment by skb1129** [comment]
@yfuks 
I have made these changes to make this package more compatible with new react native versions
Please review and merge these changes and release a new version on NPM.

**Comment by yfuks** [comment]
Hello @skb1129

Thanks for the **PR**
Will try to review it during the week.

**Comment by skb1129** [comment]
Thanks, @yfuks 
That'll be good

**Comment by yfuks** [comment]
Available in **2.1.0**

**Comment by skb1129** [comment]
@yfuks Cool, Thanks a lot!

**Pull request merged**
